#!/bin/bash

# Commit the current changes.

set -e

. scripts/common.sh

test_and_lint

message=$*

msg "Committing changes"
git add .
git commit -m "${message:-$(git rev-parse --abbrev-ref HEAD)}"
git push origin $(git rev-parse --abbrev-ref HEAD)
